name: Hello Morning
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06504
title: Cafetería y alimentos para consentirse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#52ffb6'
    - '#ff0000'
    - '#fbff5a'
    - '#ff5555'
    - '#50ab7a'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
