name: Hello Morning
favicon: null
layout_spectrum: 0.8979252555873245
typography_spectrum: 0.07407
title: Cafetería y alimentos para consentirse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4ac0c2'
    - '#bf1e2e'
    - '#ffffff'
    - '#000000'
    - '#fb7e00'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
