name: Hello Morning
favicon: null
layout_spectrum: 0.8979252555873245
typography_spectrum: 0.8575938094872981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9873380151111633
  lightness: 0.8153121985960752
  saturation: 0.39138705958612263
  rhythmicContrast: 0.7803257331252098
purpose: []
